# Generated by Django 2.1.2 on 2018-10-12 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='bucket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pots.Bucket'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
